### ISSUE TITLE
Crash when interacting with Victus Patchouli book

### ISSUE THREAD

**Issue by copygirl** [glisco03/victus#4]
At first, this error occurred to me when I selected one of the chapter icons in the book. On second launch, to confirm the issue, it happened right as the book itself was opened. Both result in the same `NoSuchFieldError: book_open`.

### Versions

Minecraft: `1.17.1`
Fabric API: `0.43.1+1.17`
Patchouli: `1.17.1-59-FABRIC`
Victus: `0.1.3+1.17.1`

### Crash

```
java.lang.NoSuchFieldError: book_open
	at com.glisco.victus.item.VictusJournalItem.method_7836(VictusJournalItem.java:32)
	at net.minecraft.class_1799.method_7913(class_1799.java:254)
	at net.minecraft.class_3225.method_14256(class_3225.java:282)
	at net.minecraft.class_3244.method_12065(class_3244.java:1086)
	at net.minecraft.class_2886.method_12550(class_2886.java:25)
	at net.minecraft.class_2886.method_11054(class_2886.java:7)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764)
	at net.minecraft.class_1255.method_18857(class_1255.java:134)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by copygirl** [comment]
It appears that the casing was changed from `book_open` to `BOOK_OPEN` some time in the 1.17 branch of Patchouli. See [1.17](https://github.com/VazkiiMods/Patchouli/blob/1.17-fabric/src/main/java/vazkii/patchouli/common/base/PatchouliSounds.java) vs [1.16](https://github.com/VazkiiMods/Patchouli/blob/1.16-fabric/src/main/java/vazkii/patchouli/common/base/PatchouliSounds.java).
